name: security alerts
on: [pull_request_target, workflow_dispatch]

jobs:
  scaning:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7.18' 
      - name: install depends
        run: npm install
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: critical
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
